version: '3.8'
services:
  squid:
    container_name: ${APP_CONTAINER_NAME}
    image: datadog/squid:${APP_VERSION}
    ports:
      - '${APP_HTTP_PORT}:3128'
    restart: always
    volumes:
      - ${VOLUMES_PATH_PREFIX}/squid/cache:/var/spool/squid
      - ${VOLUMES_PATH_PREFIX}/squid/logs:/var/log/squid
      - squid:/etc/squid
    stdin_open: true
    tty: true
    
networks:
  default:
    name: ${APP_NETWORK}
    external: true
    
volumes:
  squid:
